from pathlib import Path
import json
p=Path(__file__).resolve().parents[1]/'dist/content.js';d=json.loads(p.read_text()[12:].rstrip(';\n'));cs={c['id']:c for c in d['chapters']}
def C(ch,i,heads,rows):cs[ch]['lessons'][i]['comparison']={'heads':heads,'rows':rows}
C('1',1,['Basis','Microeconomics','Macroeconomics'],[['Unit','Individual consumer, firm, industry or market','Economy as a whole'],['Central issue','Allocation of resources','Overall output and employment'],['Analysis','Partial equilibrium','General equilibrium'],['Example','Price of one product','General price level']])
C('2',0,['Basis','Final goods','Intermediate goods'],[['Position','Crossed the production boundary; ready for final use','Used up or transformed in further production'],['National income','Count their final value','Do not add separately to final output'],['Test','Use matters','The same good can change category with its use']])
C('2',4,['Basis','Stock','Flow'],[['Time','Measured at a point in time','Measured over a period'],['Examples','Wealth, capital, inventories','Income, investment, change in stocks'],['Link','An accumulated quantity','Adds to or subtracts from a stock']])
C('3',2,['Basis','Domestic income','National income'],[['Boundary','Domestic territory','Normal residents'],['Includes','Residents and non-residents producing within the territory','Residents’ factor incomes from home and abroad'],['Bridge','Domestic income + NFIA','National income']])
C('3',5,['Basis','Nominal GDP','Real GDP'],[['Prices','Current-year prices','Base-year prices'],['Change can reflect','Quantity and price changes','Changes in output quantities'],['Use','Money value of current output','Comparison of production over time']])
C('7',2,['Basis','APC','MPC'],[['What it compares','Total consumption with total income','Change in consumption with change in income'],['Formula','C ÷ Y','ΔC ÷ ΔY'],['Can exceed 1?','Yes, when C > Y','Not in the standard consumption model with 0 < MPC < 1']])
C('8',2,['Basis','Ex-ante','Ex-post'],[['Meaning','Planned or intended','Actually realised'],['Saving and investment','May be unequal','Equal in national-income accounting'],['Adjustment','Mismatch changes unplanned inventories','Actual investment includes inventory changes']])
C('9',1,['Basis','Deficient demand','Excess demand'],[['Compared with','AD required at full employment','AD required at full employment'],['Position','AD is too low','AD is too high'],['Gap','Deflationary','Inflationary'],['Policy direction','Raise AD','Reduce AD']])
C('10',1,['Basis','Revenue receipts','Capital receipts'],[['Liability','Do not create a liability','May create a liability'],['Assets','Do not reduce assets','May reduce assets'],['Examples','Taxes, fees, dividends','Borrowing, loan recovery, disinvestment']])
C('10',3,['Basis','Revenue expenditure','Capital expenditure'],[['Asset / liability test','Neither creates assets nor reduces liabilities','Creates assets or reduces liabilities'],['Examples','Salaries, interest, pensions, subsidies','Infrastructure creation, loan repayment'],['Common trap','Recurring is not the decisive accounting test','Apply the asset/liability test']])
C('12',4,['Basis','Autonomous transactions','Accommodating transactions'],[['Motive','Independent economic reasons','Finance a BoP imbalance'],['Also called','Above-the-line items','Below-the-line items'],['Role','Determine the autonomous surplus or deficit','Help meet the resulting financing need']])
C('i4',1,['Basis','Human capital','Human development'],[['Purpose','Increase productive capacity and earnings','Improve well-being, capabilities and freedom'],['Education and health','Means to higher productivity','Valuable ends as well as means'],['Common ground','Investment in people','Investment in people']])
C('i6',2,['Measure','Who or what is counted','Important distinction'],[['Workforce','Employed people','Excludes unemployed people'],['Labour force','Employed + unemployed seeking/available for work','Excludes people outside the labour force'],['Labour supply','Hours or days of work offered','Can change without a change in headcount']])
C('i6',12,['Basis','Disguised unemployment','Seasonal unemployment'],[['Problem','Excess workers for the available work','Work unavailable in part of the year'],['Key test','Some workers can leave without reducing output','The worker has employment in one season but not another'],['Example','Too many family members on a small farm','Agricultural off-season without alternative work']])
p.write_text('window.ECON='+json.dumps(d,ensure_ascii=False,separators=(',',':'))+';\n')
a=p.parent/'app.js';s=a.read_text();s=s.replace("function lessonBody(l){", "function lessonBody(l){return lessonContent(l)+(l.comparison?comparison(l.comparison):'')}\nfunction comparison(t){return `<div class=\"comparison-wrap\"><table class=\"study-comparison\"><thead><tr>${t.heads.map(h=>`<th scope=\"col\">${esc(h)}</th>`).join('')}</tr></thead><tbody>${t.rows.map(r=>`<tr>${r.map((v,i)=>i===0?`<th scope=\"row\">${esc(v)}</th>`:`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}\nfunction lessonContent(l){")
s=s.replace("let tone=/example|case illustrates|for example/i.test(part)?'example'", "let tone=i===0&&!l.key?'definition':/example|case illustrates|for example/i.test(part)?'example'")
a.write_text(s)
