from pathlib import Path
import json,random
p=Path(__file__).resolve().parents[1]/'dist/content.js';d=json.loads(p.read_text()[12:].rstrip(';\n'))
cs={c['id']:c for c in d['chapters']}
cs['i1']['lessons'][0]['body']=cs['i1']['lessons'][0]['body'].split('\n\n')[0]+'\n\nTextbook features: stagnant economy; backward economy; dominance of agriculture; bleak industrialisation; heavy dependence on imports; limited urbanisation; semi-feudal economy. Stagnation concerns very slow growth; backwardness concerns low productivity, poverty and a weak productive structure. Semi-feudal conditions refer to the power of landlords over cultivators.'
cs['i1']['lessons'][1]['body']+='\n\nOther textbook headings: small and fragmented holdings; subsistence outlook; lack of investment in agricultural infrastructure; and the gulf between owners and tillers of the soil. Small scattered plots limited efficient cultivation, while cultivators lacked both surplus income and secure incentives to invest.'
cs['i1']['lessons'][6]['formula']='Historical indicators in your textbook: birth rate ≈48 per 1,000; death rate ≈40 per 1,000; infant mortality ≈218 per 1,000 live births; life expectancy ≈32 years; literacy below 16%; female literacy ≈7%.\nInfant mortality concerns deaths below age one per 1,000 live births—not per 1,000 total people.'
cs['i1']['lessons'][7]['body']+='\n\nThe textbook’s historical summary places about 70–75% of workers in the primary sector and about 10% in industry. Early national-income estimates were attempted by Dadabhai Naoroji, William Digby, Findlay Shirras, V.K.R.V. Rao and R.C. Desai; Rao’s study is described as especially systematic. No regular comprehensive official national-income series existed under colonial rule.'
cs['i4']['lessons'][5]['body']='Change in emotional and material environment of growth: education changes outlook and encourages innovation and the adoption of new techniques. Higher productivity of physical capital: skilled and healthy people use machinery and other resources more effectively. Higher rate of participation and equality: education and health widen people’s ability to join and benefit from development.\n\nHuman capital and growth reinforce one another: growth provides resources for education and health, which then support further growth. Schooling years and literacy rates are useful indicators, but cannot fully measure the quality of skills and capabilities.'
cs['i4']['lessons'][6]['body']=cs['i4']['lessons'][6]['body'].replace('Insufficient on-the-job training limits practical capability.', 'Insufficient on-the-job training in the primary sector limits practical capability.')
cs['i4']['lessons'][9]['body']+='\n\nA steep education pyramid means progressively fewer learners reach higher levels of education. Degree-oriented education without vocational skills can produce a mismatch between qualifications and jobs. The poverty–illiteracy cycle works both ways: poverty restricts schooling, and inadequate education restricts earning opportunities.'
cs['i5']['lessons'][0]['body']=cs['i5']['lessons'][0]['body'].replace('Rural development is a comprehensive process of improving the economic and social conditions of people in rural areas.', 'Rural development means an action-plan for addressing the economic, social and environmental issues of the rural economy.')
cs['i5']['lessons'][9]['body']+='\n\nTextbook merit headings: discards the use of non-renewable resources; environment-friendly; sustains soil fertility; healthier and tastier food; inexpensive technology for small and marginal farmers. India’s comparative advantage is its abundant labour because organic methods can be labour-intensive. Remember these exam headings while recognising that actual yields, nutritional outcomes and costs depend on farming conditions.'
cs['i6']['lessons'][9]['body']=cs['i6']['lessons'][9]['body'].replace('insufficient investment and low labour mobility', 'low savings and investment, the joint family system and limited mobility of labour')
cs['i6']['lessons'][10]['body']+='\n\nOther textbook initiatives: NRLM supports rural livelihoods and self-help groups; rural roads improve access to work and markets; Skill India/PMKVY build employable skills; MUDRA supports small-business credit; and Start-up India encourages entrepreneurship. Learn the employment mechanism rather than assuming every historical scheme in the box remains active today.'
for c in d['chapters'][12:]:
 for j,l in enumerate(c['lessons']):
  q=next(q for q in d['questions'] if q['id']==f"ied-theory-{c['number']}-{j}")
  q['solution']=l['textbookHeading']+'\n'+l['body'].replace('\n\n','\n')+ ('\n'+l['formula'] if l['formula'] else '')
r=random.Random(8765)
for q in d['questions']:
 if q['type']=='mcq':
  indexes=list(range(4));r.shuffle(indexes);old=q['options'];q['options']=[old[i] for i in indexes];q['answer']=indexes.index(q['answer'])
p.write_text('window.ECON='+json.dumps(d,ensure_ascii=False,separators=(',',':'))+';\n')
