"""Restore textbook point lists and explanations; keep diagram lesson indices stable."""
from pathlib import Path
import json,re
root=Path(__file__).resolve().parents[1];p=root/'dist/content.js';d=json.loads(p.read_text()[12:].rstrip(';\n'));cs={c['id']:c for c in d['chapters']};changed=[]
def U(ch,index,section,title,lead,items,kind='Concept'):
 c=cs[str(ch)]
 if index is None:
  key='restored-'+re.sub('[^a-z0-9]+','-',title.lower()).strip('-')
  l=next((x for x in c['lessons'] if x.get('key')==key),None)
  if l is None:l={'formula':''};c['lessons'].append(l)
 else:l=c['lessons'][index]
 l.update(title=title,textbookHeading=section,kind=kind,key='restored-'+re.sub('[^a-z0-9]+','-',title.lower()).strip('-'),body=lead+'\n\n'+'\n\n'.join('**'+h+':** '+t for h,t in items),blocks=[dict(title='Core idea',text=lead,tone='definition')]+[dict(title=h,text=t,tone='point') for h,t in items])
 changed.append((str(ch),l))
U(1,3,'1.3.1 Area of Study (Scope) of Macroeconomics','Scope of macroeconomics: all six areas','Scope means the field of study. The chapter identifies six leading areas; each needs its own heading and explanation.',[
('1 · Estimation of National Income and Related Aggregates','Macroeconomics begins with national income and measures the economy’s overall economic activity. It estimates related aggregates such as Gross Domestic Product (GDP) and Net Domestic Product (NDP), allowing comparison of output and income over time.'),
('2 · Theory of Employment','It studies employment and unemployment in the economy. Keynesian theory explains why inadequate aggregate demand can leave willing workers unemployed, and identifies remedies for restoring output and employment.'),
('3 · Theory of Money','It studies money and the creation of credit by commercial banks. It also examines the central bank’s role—in India, the RBI—in regulating money supply and credit in the economy.'),
('4 · Theory of General Price Level','It explains movements in the general price level, including inflation and deflation. Inflation is a persistent increase in the general price level; deflation is a persistent decrease. A change in one product’s price is different from a change in the economy-wide price level.'),
('5 · Government Budget','It studies how government receipts and expenditure affect the level of economic activity. Through taxation, public spending and borrowing, budgetary policy influences aggregate demand, employment, growth and economic stability.'),
('6 · Exchange Rate and Balance of Payments','It studies the determination and management of the foreign exchange rate. Balance of payments records a country’s economic transactions with the rest of the world, connecting the domestic economy with international trade, income and financial flows.')])
U(1,None,'1.3.2 Significance of Macroeconomics','Significance of macroeconomics: all six points','Significance explains why studying these economy-wide relationships is useful. Keep these six headings separate from the six areas of scope.',[
('1 · Description of the Economy','National-income estimates across sectors reveal the nature and level of economic activity. Unemployment data show the extent of the employment problem and help identify remedies. The government budget shows how the state regulates economic activity. Together these provide a systematic picture of the economy’s performance.'),
('2 · Roadmap for Business Decisions','The description of the economy helps businesses decide whether to expand investment and production. For example, rising national income and consumer expenditure suggest stronger demand; firms may invest more, expanding output and employment. Macroeconomic conditions therefore guide individual business decisions.'),
('3 · Policy Formulation','Macroeconomic data help governments design policies and programmes. For example, information about people below the poverty line helps target Direct Benefit Transfer (DBT): money is transferred directly to beneficiaries’ linked bank accounts. The policy should respond to the scale and nature of the problem identified.'),
('4 · Global Economic Issues','It brings international issues into view, including exchange rates and the movement of Foreign Direct Investment (FDI) between countries. These affect trade, financing, productive capacity and the relationship between the domestic economy and the rest of the world.'),
('5 · Environmental Pollution and Sustainable Development','Macroeconomic analysis helps assess environmental costs and formulate a strategy of sustainable development. Sustainable development meets development needs without depleting the resources available to future generations; output growth must therefore be assessed alongside its environmental consequences.'),
('6 · Structural Changes and Growth Path of the Economy','It helps identify changes in the economy’s structure and trace the nature and pace of growth. Changes in occupational structure—for example, workers moving from agriculture towards industry and services—show how development is changing the economy, beyond an increase in total GDP.')])
U(1,1,'1.2 Microeconomics versus Macroeconomics','Micro versus macro: seven bases of distinction','Both study scarcity and choice, but at different levels. An industry aggregates firms, yet studying one industry is still microeconomics.',[
('1 · Concept','Microeconomics studies individuals, households, firms and industries; macroeconomics studies the economy as a whole.'),
('2 · Central Issue','Micro focuses on allocation of resources: consumers maximise satisfaction and producers maximise profit. Macro focuses on overall output and employment, and policies that maximise growth with stability.'),
('3 · Economic Variables','Micro uses variables such as an individual consumer’s demand and a producer’s supply. Macro uses aggregate demand, aggregate supply, national income, economy-wide consumption, investment and employment.'),
('4 · Aggregation of Economic Units','Micro involves limited aggregation, such as all firms in one industry. Macro involves the wider aggregation of economic units across the whole economy.'),
('5 · Economic Agents','Micro emphasises individual agents such as consumers and producers pursuing personal gains. Macro examines institutional decision makers such as the RBI, government and regulators, whose policies affect growth and stability.'),
('6 · Method of Study','Partial equilibrium studies one market assuming other markets unchanged. General equilibrium studies simultaneous equilibrium and interdependence across markets. The textbook associates the former with micro and the latter with macro.'),
('7 · Assumptions of Study','In the textbook’s simplified comparison, micro takes overall output and employment as given while studying allocation and distribution; macro varies overall output and employment while taking distribution as given. These are analytical assumptions, not a claim that macro can never study inequality.')])
U(1,None,'Ability Zone · Emergence of Macroeconomics','Why the Great Depression challenged classical economics','The Great Depression of the 1930s explains why macroeconomics emerged as a distinct field, rather than simply applying individual-market reasoning to the whole economy.',[
('Classical belief: individual gains and social welfare','Classical reasoning argued that individuals pursuing self-interest maximise their satisfaction; together this was expected to maximise social welfare and ensure optimal use of scarce resources.'),
('Classical belief: automatic full employment','Competitive markets were expected to move to equilibrium. If labour supply exceeded demand, falling wages were expected to reduce supply and raise demand until full employment returned. Full employment was therefore treated as the normal condition.'),
('What the Depression showed','The textbook’s historical example reports US unemployment rising from about 3% to 25% during 1929–33, alongside a roughly one-third fall in GDP. Persistent unemployment contradicted the expectation of rapid automatic recovery.'),
('Low Level Equilibrium Trap','Low AD → low planned output → low employment → low GDP/income → low AD again. Firms could settle at an equilibrium with widespread unused capacity; market adjustment did not necessarily break the cycle.'),
('Keynes’s diagnosis and remedy','Keynes identified inadequate aggregate demand as the central problem and advocated large-scale government expenditure to raise demand. His 1936 General Theory of Employment, Interest and Money established the modern macroeconomic approach.')],kind='Ability Zone')
U(2,None,'2.3.2 Components of Investment · Significance','Fixed investment and inventory investment: why each matters','Investment adds to capital. Fixed investment concerns productive assets; inventory investment concerns changes in stocks of inputs and output.',[
('Fixed Investment','An increase in producers’ fixed assets, such as plant and machinery, adds productive capacity. For example, increasing a stock from eight to ten machines adds two machines. Higher capacity supports higher output and economic growth.'),
('Inventory Investment','Inventory includes raw materials, semi-finished goods and finished goods. Inventory investment is closing inventory minus opening inventory; it can be positive or negative. It is a flow even though inventory itself is a stock.'),
('Why keep raw-material stocks?','They ensure uninterrupted supplies of inputs and reduce the need for daily market purchases. This protects production against uncertainty about input prices and availability.'),
('Why keep finished-goods stocks?','They enable producers to meet expected future demand promptly. Desired inventory is planned; undesired inventory accumulates when sales fall short of expectations and can impose losses.'),
('Significance of Net Investment','Net investment adds to the existing capital stock, expands productive capacity and creates employment opportunities. Gross investment also includes replacement of worn-out assets, so a large gross figure does not necessarily imply a large net expansion.')])
U(2,None,'2.7.2–2.7.4 Circular Flow of Income','Circular flow: three phases, assumptions and significance','Production, income generation and expenditure form an unending circular flow. Each phase leads to the next, giving three ways of measuring the same economic activity.',[
('1 · Phase of Production','Producers hire land, labour, capital and entrepreneurship from households and use these with intermediate inputs to add value. Turning wood worth ₹5,000 into chairs worth ₹10,000 creates ₹5,000 of value added.'),
('2 · Phase of Income Generation / Distribution','Value added becomes factor income: rent for land, wages and salaries for labour, interest for capital and profit for entrepreneurship. What firms pay as factor payments, households receive as factor incomes.'),
('3 · Phase of Disposition / Expenditure','Income is spent on final goods: household consumption and producers’ investment. Expenditure creates demand, inducing further production. Thus production generates income, income finances expenditure, and expenditure supports production.'),
('Assumptions of the Simple Two-Sector Model','Only households and producers exist; households spend their entire income, so there is no saving; the economy is closed, so there are no exports or imports; and there is no government. State these when explaining the simplest circular-flow diagram.'),
('Triple Identity','Value of production = income generated = expenditure on final output. Money flows express the value of real flows and move in the opposite direction to goods and factor services.'),
('Significance: Estimation of National Income','Circular flow explains the production, income and expenditure approaches. Measure value added, sum factor incomes, or sum final expenditure; each views the same flow from a different angle.'),
('Significance: Intersectoral Interdependence','Households depend on producers for goods and income; producers depend on households for factor services and demand. The model makes these mutual dependencies visible.')])
U(2,None,'2.3.3 Depreciation Reserve Fund','Depreciation, replacement and the reserve fund','Depreciation is consumption of fixed capital: loss of value while fixed assets are used. Replacement maintains capacity; net investment expands it.',[
('Normal Wear and Tear','Repeated use wears out machines and other fixed assets. A part of gross investment must replace the capital consumed rather than expand the stock.'),
('Accidental Damage and Expected Obsolescence','The chapter includes normal accidental damage and expected obsolescence due to changes in technology or demand. Unexpected catastrophic destruction is a capital loss, distinguished from normal depreciation.'),
('Depreciation Reserve Fund','Producers set aside funds to replace worn-out fixed assets. With a ₹10 lakh machine and an expected ten-year life, ignoring scrap value, an annual provision of ₹1 lakh finances replacement at the end of its life.'),
('Why the fund matters','Without replacement finance, productive assets deteriorate and capacity may fall. Lower investment can reduce output, income and employment, contributing to economic slowdown. Gross investment = net investment + depreciation.')])
U(3,6,'3.7.1 Limitations of GDP as an Index of Welfare','GDP and welfare: all four limitations','Real GDP growth can increase the goods and services available to people. However, the textbook gives four separate reasons why GDP is an incomplete index of welfare.',[
('1 · Distribution of Income','If additional income is concentrated among the rich, rising GDP need not improve living standards for most people. An increasing divide between rich and poor can coexist with high aggregate growth.'),
('2 · Composition of GDP','What is produced matters. More defence goods can contribute indirectly through security, but do not directly increase household consumption. A rise in luxuries for the rich while necessities remain scarce may do little for broad welfare.'),
('3 · Non-monetary Exchanges / Transactions','Barter and payments in kind may go unrecorded or be inadequately measured, understating output and making GDP a weaker welfare measure. Production for own consumption is conceptually included where it can be imputed; absence of cash does not automatically make productive activity non-economic.'),
('4 · Externalities','Externalities are benefits or costs imposed on others without a price or compensation. A neighbour enjoys a beautiful garden without paying: positive externality. Factory smoke or polluted water harms others without adequate compensation: negative externality. GDP does not directly adjust for these unpriced welfare effects.')])
U(3,None,'3.2.2 Domestic Territory · 3.2.4 Domestic Product','Domestic territory and why product equals income','Domestic territory is an economic accounting boundary, not simply the geographical land within political borders.',[
('Geographical Territory and Economic Activity','It includes territory administered by the government within which persons, goods and capital circulate, subject to the accounting conventions used in the chapter.'),
('Embassies and Establishments Abroad','Include the country’s embassies, consulates and military establishments abroad. Exclude foreign embassies and international organisations situated within its geographical borders.'),
('Ships and Aircraft','Include ships and aircraft operated by residents between countries under the domestic-territory convention. Physical movement across a border does not by itself change the operator’s economic territory.'),
('Fishing Vessels and Floating Platforms','Include resident-operated fishing vessels, oil and gas rigs and floating platforms in international waters, and the relevant extraction rights specified in the accounting convention.'),
('Domestic Product = Domestic Income','Production creates value added, and value added is distributed as factor income. Thus the product and income are two views of the same activity, provided the gross/net and price basis are consistent.')])
U(4,1,'4.2.2 Precautions · 4.2.3 Double Counting','Value-added method: all inclusions and exclusions','Count value created during the current year once. Both the inclusion decision and the reason are important in theory and classification questions.',[
('Include: Commission on Second-hand Goods','The old good itself was counted when produced, but the broker’s current service is new production and must be counted.'),
('Include: Own-account Production','Goods made by a producing unit for its own use are included. A car producer using a newly produced car to transport employees still creates current output.'),
('Include: Goods for Self-consumption','Impute the value of goods such as wheat produced and consumed by a farming family. Not being sold does not mean that the good was not produced.'),
('Include: Imputed Rent','An owner-occupied house provides housing services just as a rented house does. Its imputed rent is included.'),
('Exclude: Resale of Second-hand Goods','Reselling an existing asset creates no new output of that asset in the current year. Include only any current service involved in the sale.'),
('Exclude: Intermediate Goods as a Separate Addition','Their value is already embodied in final output. Either count final goods or sum value added at each stage, never add both.'),
('Exclude: Own-household Domestic Services','Unpaid domestic services within one’s own household are excluded under the textbook’s measurement convention. Paid domestic services are different.'),
('Illegal Activities: Textbook Treatment','The chapter excludes these from its measured estimates because reliable recorded data are unavailable. Use this stated treatment for its classification questions.'),
('Double Counting Example','Wheat ₹100 → flour ₹160 → bread ₹250. Values added are ₹100, ₹60 and ₹90, totalling ₹250. Adding sales of all three stages gives ₹510 and counts the same intermediate value repeatedly.')])
U(4,3,'4.3.2 Precautions Regarding Income Method','Income method: all inclusions and exclusions','Include income earned from current productive services. Distinguish a productive reward from a transfer, an asset transaction or a capital gain.',[
('Include: Retirement Pension','An employment-related retirement pension is treated as compensation for past service in the chapter. It differs from a welfare old-age pension, which is a transfer.'),
('Include: Current Commissions and Brokerage','Commission on second-hand goods and brokerage on shares or bonds are rewards for current services. The sale price of the old asset or financial security itself is not factor income.'),
('Include: Imputed Rent and Self-consumption','Owner-occupied housing services and goods produced for own consumption generate current income even when no cash sale occurs.'),
('Include: Productive Interest','Interest paid by producing units on capital borrowed for production is factor income. Interest on consumption loans is excluded in the textbook treatment.'),
('Exclude: Transfer Earnings','Welfare pensions, unemployment allowances, scholarships and pocket money have no corresponding productive service and are not national income.'),
('Exclude: Illegal Income, Windfall and Capital Gains','The chapter excludes unrecorded illegal income; lottery winnings and gains from asset-price changes are not rewards for current production.'),
('Exclude: Spending from Accumulated Savings','The transfer or use of earlier savings does not itself create current factor income. Count any current goods or services purchased through the relevant production accounts instead.'),
('Exclude: Indirect Taxes from Factor-cost Income','Indirect taxes are part of market prices but not rewards paid to factors. Deduct net indirect taxes when converting market-price output to factor-cost income.'),
('Avoid Repeating Profit Components','Corporate tax, dividends and retained earnings together form profit. If total profit is supplied, do not add those components again. Likewise, do not add rent or interest again if operating surplus already includes them.')])
U(4,None,'4.4.2 Precautions Regarding Expenditure Method','Expenditure method: the complete precautions','Final spending on current domestic output counts. A transaction moving money or ownership is not automatically expenditure on newly produced goods and services.',[
('Include: Final Expenditure','Include private consumption, government final consumption, gross domestic capital formation and net exports. Investment includes fixed capital and change in inventories.'),
('Include: Brokerage and Commission','Current brokerage on financial securities and commissions on second-hand goods purchase new services, even though the underlying asset purchase is excluded.'),
('Include: Imputed Expenditure','Include the imputed value of goods produced for own consumption and owner-occupied housing services.'),
('Exclude: Intermediate Expenditure','Its value is already included in final expenditure. Adding it separately would double count the same output.'),
('Exclude: Second-hand Purchases','These purchase output produced in an earlier period. They do not add current output, apart from current sale-related services.'),
('Exclude: Financial-asset Purchases','Buying shares, debentures and bonds exchanges financial claims. It does not itself purchase a newly produced final good or service.'),
('Exclude: Transfer Payments','Welfare pensions and scholarships transfer purchasing power without corresponding value addition. A later purchase of current output using that money is a separate transaction.'),
('Net Exports and Stocks','Subtract imports to remove foreign output contained in expenditure. Add inventory change only if it is not already included in gross domestic capital formation.')])
U(5,2,'5.3 Functions of Money · Critical Terms','Functions of money and why each matters','Money has two primary functions and three secondary functions. Explain the function, illustrate it, and connect it to the economic benefit.',[
('Primary 1 · Medium of Exchange','Money is accepted between sale and purchase, removing the need for a double coincidence of wants. A farmer can sell wheat for money and later buy clothing from someone else. This expands exchange and markets, encourages production for sale rather than only self-consumption, and supports GDP growth.'),
('Primary 2 · Measure of Value / Unit of Account','Prices express different goods, services and assets in a common unit. This permits value comparisons, national-income estimation and price-index construction. A common unit also makes asset markets and investment decisions easier.'),
('Secondary 1 · Standard of Deferred Payments','Future debts, principal and interest can be expressed and settled in money. Repaying a monetary amount is simpler than returning goods of exactly the original quality. This supports financial markets, lending, consumption and investment.'),
('Secondary 2 · Store of Value','Money carries purchasing power into the future without the physical deterioration associated with many stored goods. Convenient saving can finance future investment; inflation nevertheless erodes real purchasing power. Saving supports growth when channelled into productive investment, while a widespread cut in spending can weaken demand.'),
('Secondary 3 · Transfer of Value','Money allows purchasing power to move between people, regions and countries. This supports capital mobility, global financial markets, multinational enterprises and foreign investment, and can help finance development in capital-scarce regions.'),
('Static versus Dynamic Functions','Static functions are these conventional exchange, value and payment functions. Dynamic functions concern money’s role in economic stability and growth: regulating its supply can restrain inflation or support demand during slowdown.')])
U(5,None,'5.1.2 Evolution of Money · Digital Currency Box','Evolution of money: stages, gains and limitations','The chapter traces a journey from barter to metallic currency, paper money, plastic money and electronic payments. Each stage eases some earlier difficulties while creating new issues.',[
('1 · Barter System','Goods exchange directly for goods, without money prices. Selling and buying must occur together, limiting exchange mainly to mutually matched needs. The chapter contrasts its lack of monetary-price uncertainty with its severe limits on trade.'),
('2 · Metallic Currency','Gold, silver and later alloy coins separate sale from purchase and expand markets. However, large payments are cumbersome, and convenient small denominations can be difficult.'),
('3 · Paper Money','Money supply becomes more elastic and easier to expand than a supply tied to metal. This supports national and international markets and investment. Excessive or insufficient expansion can create inflationary or deflationary pressures.'),
('4 · Plastic Money and e-Money','Cards, electronic transfers, wallets and digital banking make payments convenient and can broaden financial inclusion while reducing dependence on printed currency. Cybercrime, fraud and access problems require attention.'),
('Digital Payments, Bitcoin and CBDCs','A card or bank transfer is a method of accessing/transferring money. Bitcoin is a decentralised digital asset whose value responds to market demand and supply. A Central Bank Digital Currency is issued by the central bank and combines a digital form with state backing. These are different concepts, not interchangeable labels.'),
('Changing Role of Money','Initially a medium of exchange, money also became a unit of value, a store of purchasing power and a standard for future payments. “Money is what money does” expresses this functional approach.')],kind='Concept and box')
U(5,4,'5.4 Ability Zone · Monetary Measures and Liquidity','M2, M3, M4 and liquidity','Broader money measures add less immediately spendable components to the most liquid measure, M1. These are stock measures at a point in time.',[
('M1 · The Starting Point','Currency with the public + demand deposits with commercial banks + other eligible deposits with the RBI. Government and interbank holdings are excluded from money held by the public.'),
('M2','M1 + deposits with Post Office Savings Bank accounts.'),
('M3 · Aggregate Monetary Resources','M1 + net time deposits with commercial banks. The chapter calls M3 aggregate monetary resources.'),
('M4','M3 + total deposits with post offices, excluding National Savings Certificates.'),
('Narrow versus Broad Money','The chapter groups M1/M2 as narrow-money concepts and M3/M4 as broad-money concepts. Specify which measure is being used before comparing money supply.'),
('Liquidity','Liquidity means ease and speed of conversion into cash. Currency is the most liquid asset; demand deposits are readily usable through payment instructions. Time deposits are less immediately accessible, so broader measures include less-liquid components.')],kind='Ability Zone')
U(5,None,'5.4.3 Suppliers of Money · Critical Terms','Who supplies money? Bank money and high-powered money','Distinguish the institutions creating money, the money held by the public, and the monetary base supporting deposit creation.',[
('1 · Central Bank','The RBI is the principal currency-note issuing authority in the textbook’s account. Note issue follows the minimum reserve system described in the chapter.'),
('2 · Commercial Banks','They do not print notes or mint coins, but create demand deposits through lending. These chequeable deposits serve as bank money.'),
('3 · Government','The chapter identifies the Ministry of Finance as issuer of ₹1 notes and coins. Distinguish this issue authority from the RBI’s circulation and distribution functions.'),
('High-powered Money / Monetary Base','Currency with the public + banks’ vault cash + cash reserves held by banks with the RBI. It supports the banking system’s ability to create deposits.'),
('Why It Differs from Money Supply','Currency with the public belongs to both concepts, but banks’ own cash and reserves are not part of money held by the public. Demand deposits belong to money supply and are supported by the monetary base.'),
('Ideal Supply of Money','The chapter describes an ideal supply as one consistent with the supply of goods and services, avoiding both inflationary pressure and deficient-demand conditions.')],kind='Concept and box')
U(5,None,'Ability Zone · Indian Monetary System','Paper currency, legal tender and minimum reserves','India’s textbook monetary system is described as a paper currency standard, even though coins also circulate. Its notes and coins are credit money because face value exceeds material value.',[
('Limited and Unlimited Legal Tender','The chapter contrasts coins, accepted up to the prescribed legal limit, with paper notes as unlimited legal tender. “Unlimited” concerns the value of debt settled under the applicable conditions, not an entitlement to pay with withdrawn or invalid notes.'),
('Minimum Reserve System','The textbook gives a minimum reserve of ₹200 crore in gold and foreign securities, including at least ₹115 crore of gold. This is a minimum backing requirement, not a rule that reserves must equal a fixed percentage of all currency issued.'),
('No Conversion into Bullion','Holding currency does not entitle the holder to demand its face value in gold or silver from the issuing authority. Gold backing and convertibility into gold are different ideas.')],kind='Ability Zone')
U(6,2,'6.3.2 Functions of the Central Bank','Central bank: all seven functions explained','The central bank is the apex institution controlling and regulating the banking and monetary system. Its objective is growth with stability rather than the commercial bank’s private profit.',[
('1 · Issuer of Currency','It has the principal monopoly of note issue, subject to the government’s ₹1-note/coin exception described in Money. Centralised issue creates uniformity, public confidence, a central check on supply and flexibility to respond to inflation or deflation. The earnings from issue accrue to the public authority.'),
('2 · Banker to the Government','As banker, it maintains accounts, accepts deposits, makes payments and transfers funds. As agent, it manages the issue, purchase, sale and redemption of government securities and debt. As financial adviser, it advises on monetary and financial conditions, stability and borrowing.'),
('3 · Bankers’ Bank and Supervisory Role','It holds commercial banks’ reserve deposits and provides financial accommodation. It supervises compliance with directives and reserve requirements such as CRR and SLR, thereby influencing credit creation.'),
('4 · Lender of Last Resort','A bank unable to obtain emergency finance elsewhere can approach the central bank against eligible security. This protects confidence, helps prevent a liquidity problem spreading and supports monetary-system stability.'),
('5 · Custodian of Foreign Exchange','It holds and manages official foreign-exchange reserves and may buy or sell foreign currency to moderate exchange-rate instability under managed floating.'),
('6 · Clearing House Function','Banks settle mutual claims through accounts with the central bank. For example, offsetting cheques between two banks allows only the net amount to be settled, avoiding unnecessary cash transfers and reducing cash requirements.'),
('7 · Control of Credit','It regulates the cost and availability of bank credit. In the textbook framework, tighter credit restrains inflationary demand and easier credit supports activity during deficient demand. Quantitative tools affect overall credit; qualitative tools target particular uses or sectors.')])
U(6,None,'6.1 Critical Terms · Central versus Commercial Banks','Banks, financial institutions and central-bank differences','A financial institution is not automatically a bank. The chapter’s banking test combines acceptance of chequeable deposits with lending or advances.',[
('All Financial Institutions Are Not Banks','The chapter uses LIC as a lender that does not accept chequeable public deposits and ordinary post-office savings as deposit-taking without the paired commercial-lending function. Accepting a deposit or lending alone does not satisfy its two-function definition.'),
('Customers and Position','A commercial bank serves households and businesses; the central bank stands at the apex and mainly serves government and the banking system.'),
('Role in Money Supply','The central bank issues currency; commercial banks create deposit money through loans. Credit creation is not currency printing.'),
('Role in Foreign Exchange','The central bank is custodian of official reserves and manages exchange-rate interventions. Commercial banks deal in foreign exchange as part of customer services and business.'),
('Objectives','Commercial banks seek profit subject to regulation. The central bank aims at monetary stability and growth, supervising the system rather than competing as an ordinary retail bank.')],kind='Concept and box')
U(6,3,'6.4.1 Quantitative Instruments of Credit Control','Quantitative credit controls: rates and open-market operations','Quantitative controls influence overall credit rather than one selected activity. For each instrument, explain the action, the effect on bank funds or borrowing cost, and the resulting effect on spending.',[
('Bank Rate','The textbook describes this as the rate for central-bank lending to commercial banks, distinguished from secured short-term repo transactions. Raising it tends to raise borrowing costs and restrain credit; lowering it tends to encourage credit.'),
('Open Market Operations','The central bank buys or sells government securities in the open market. Purchases inject funds and support bank lending; sales absorb funds and reduce lending capacity. Remember the action from the central bank’s viewpoint: buying adds liquidity, selling withdraws it.'),
('Repo Rate','Repo is lending against securities under an agreement to reverse the transaction at a specified date and price. A higher repo rate makes central-bank funds costlier and can raise bank lending rates, reducing demand for credit. Lowering it works in the opposite direction.'),
('Reverse Repo Rate','This is the rate associated with banks placing funds with the central bank through reverse-repurchase arrangements. A higher return can encourage banks to park more funds rather than lend; lowering it can encourage lending. The effect depends on banks’ alternative uses for funds.'),
('Cost versus Availability','Rates mainly influence the cost and attractiveness of funds. Open-market operations and reserve requirements influence available liquidity. Both channels ultimately affect credit, investment, consumption and aggregate demand.')])
U(6,4,'6.4.1–6.4.2 Reserve Ratios and Qualitative Instruments','CRR, SLR and all three selective controls','Reserve requirements influence lending capacity; selective controls influence which uses receive credit. State both the direction of the policy and its mechanism.',[
('Cash Reserve Ratio (CRR)','The prescribed share of bank deposit liabilities held as cash reserves with the RBI. Raising CRR leaves a smaller share available to support lending and reduces the simple credit multiplier; lowering it expands potential credit creation.'),
('Statutory Liquidity Ratio (SLR)','The prescribed share of relevant liabilities held by the bank in eligible liquid assets such as cash, gold and approved unencumbered securities. A higher SLR restrains funds available for other lending; a lower SLR can release funds. CRR is held with the RBI; SLR assets are maintained by the bank.'),
('1 · Margin Requirement','Margin is collateral value minus the loan granted. With collateral worth ₹1 crore and a loan of ₹80 lakh, the margin is ₹20 lakh or 20%. Raising the margin reduces the maximum loan for given collateral, particularly restraining speculative borrowing; lowering it permits more credit.'),
('2 · Rationing of Credit','Fix quotas or limits on credit for selected business activities. Tighter quotas restrict lending to those uses; relaxation increases availability. This is selective credit control.'),
('3 · Moral Suasion','The central bank uses advice, persuasion and pressure to obtain banks’ cooperation. It may urge restraint during inflation and more liberal lending during deficient demand. The chapter notes that it can affect both overall and selected credit, though usually classified as qualitative.')])
U(6,5,'Ability Zone · Success of Repo Policy and OMO','When monetary tools work: all success conditions','Changing a policy instrument does not guarantee a proportionate change in lending or spending. The chapter separates four conditions for repo-rate policy and two for open-market operations.',[
('Repo 1 · Dependence on the Central Bank','Banks with ample funds of their own depend less on central-bank loans, so a change in the repo rate may have a weaker influence.'),
('Repo 2 · Sensitivity of Demand for Funds','Banks may not respond strongly to small rate changes when business expectations or credit demand are weak. A cheaper source of funds does not by itself create willing borrowers.'),
('Repo 3 · Structure of Interest Rates','If non-bank financial institutions do not adjust their rates correspondingly, borrowers can switch sources and weaken policy transmission.'),
('Repo 4 · Overall Supply of Funds','When non-bank sources are popular and readily available, regulating the price of bank funds has less influence on total financing.'),
('OMO 1 · Existence of a Securities Market','Open-market purchases and sales require a well-organised, functioning market for government securities. Without willing counterparties, operations have limited reach.'),
('OMO 2 · Excess Reserves with Banks','Large excess reserves can weaken the intended relationship between liquidity withdrawal and lending. Banks can absorb a drain without proportionately reducing loans, while injections may remain idle when demand for credit is low.')],kind='Ability Zone')
U(7,None,'7.1–7.3 Aggregate Demand and Aggregate Supply','AD and AS: assumptions, components and schedules','In this course, AD is planned expenditure measured against income, and AS is planned output. The diagram’s axes and assumptions determine how the curves are interpreted.',[
('AD Means Planned Expenditure','AD is the expenditure buyers intend to incur on domestically produced goods and services during an accounting year. It is not the sum of physical quantities of different goods, nor necessarily actual expenditure.'),
('AD at Zero Income','Some consumption is necessary even when current income is zero. It is financed from past saving or borrowing. This autonomous expenditure makes the AD curve start above the origin.'),
('Two-, Three- and Four-Sector Components','In a two-sector closed economy AD = C + I. Add government for AD = C + I + G. In an open economy AD = C + I + G + (X − M). Exports add demand for domestic output; imports remove spending on foreign output.'),
('AD Schedule and Curve','The schedule lists planned expenditure at different income levels. With income on the horizontal axis, consumption and AD rise as income rises. This upward-sloping income–expenditure curve differs from an AD curve drawn against the general price level.'),
('AS, Income and the 45° Line','Planned production creates income, so AS is represented by Y. With the same scale on both axes, the 45° line represents equality between output/income and expenditure.'),
('Model Conditions','Technology and relevant prices are treated as constant; spare capacity allows output to respond to demand before full employment. At full employment, real output cannot keep rising merely because planned spending rises.')])
U(7,None,'7.4 Consumption Function · Critical Terms','Consumption function: every diagram observation','The consumption function relates household consumption to income: C = C̄ + bY, where C̄ is autonomous consumption and b is MPC.',[
('Autonomous Consumption','C̄ is consumption when Y = 0. The curve starts above the origin on the consumption axis, and saving at zero income is −C̄.'),
('Induced Consumption','bY is consumption attributable to income. Higher income raises consumption; the amount consumed out of an additional unit of income is MPC.'),
('Keynes’s Psychological Law','As income rises, consumption rises by less than the increase in income, leaving part for saving. In the standard linear model, 0 < MPC < 1 and the consumption line is flatter than the 45° reference line. Constant MPC means equal increments of income produce equal increments of consumption.'),
('Break-even Point','Where the consumption line crosses C = Y, all income is consumed and saving is zero. Below that income, C > Y and households dissave; above it, C < Y and saving is positive.'),
('Slope versus Average','The consumption-line slope is MPC = ΔC/ΔY. APC = C/Y is the slope of a ray from the origin to a point on the line, not the slope of the consumption line itself.'),
('Why APC Falls in the Linear Model','APC = C̄/Y + MPC. As income rises, the autonomous-consumption term becomes smaller relative to income, so APC falls towards MPC when C̄ is positive.')])
U(7,None,'7.5 Saving Function · Ability Zone','Deriving saving and consumption curves from one another','Consumption and saving exhaust income: Y = C + S. Use this identity to derive either function and check their common break-even income.',[
('Consumption to Saving','From C = C̄ + bY, S = Y − C = −C̄ + (1 − b)Y. The saving intercept is the negative of autonomous consumption and the saving slope is MPS = 1 − MPC.'),
('Saving to Consumption','From S = a + mY, C = Y − S = −a + (1 − m)Y. A negative saving intercept produces a positive consumption intercept.'),
('Locate the Two Intercepts','At Y = 0, consumption is C̄ and saving is −C̄. Mark these on their respective vertical axes; do not start both curves at the origin.'),
('Locate the Shared Break-even Income','Set S = 0 or C = Y. Both give Y = C̄/(1 − b). The saving line crosses the income axis directly below the consumption line’s intersection with the 45° line.'),
('Complete the Curves','Draw consumption with slope b and saving with slope 1 − b. The slopes add to one; below break-even income saving is negative, and above it saving is positive.'),
('Undefined Ratios at Zero Income','APC and APS divide by Y and are undefined when income is zero. MPC and MPS concern changes and can remain well defined; do not report an ordinary finite APC or APS at zero income.')],kind='Ability Zone')
U(8,None,'8.2 Equilibrium Output · Planned and Actual Stocks','Equilibrium: conditions, stock signals and the two approaches','Equilibrium requires intended output to equal intended expenditure. The producer’s desired inventory may be positive; equilibrium means no unintended change in it, not zero stocks.',[
('AD = AS Approach','At equilibrium, Y = C + I in the two-sector model. Intended purchases match intended production, actual stocks equal desired stocks, and producers have no reason to change output.'),
('S = I Approach','Since Y = C + S and AD = C + I, equating Y and AD gives C + S = C + I, hence planned S = planned I. Saving is a leakage and investment an injection; equilibrium requires their equality.'),
('When AS > AD','Actual stocks exceed desired stocks. Firms cut planned production and employment. Falling income reduces saving until planned S equals planned I.'),
('When AD > AS','Stocks fall below the desired level, and some demand goes unfulfilled. With spare capacity, firms expand production and employment; income and saving rise towards equilibrium.'),
('Equilibrium Is Not Necessarily Full Employment','Spending plans can match production plans while workers remain involuntarily unemployed. Full-employment equilibrium additionally requires fuller utilisation of available resources.'),
('Ex-post Identity Is Different','Actual investment includes unplanned inventory changes, so actual saving and actual investment are equal in accounting. This identity holds even when planned saving and investment differ.')])
U(9,None,'9.2.3 Causes of Deficient Demand','Deficient demand: all six causes','Deficient demand means planned AD is below the level required for full employment. Start from AD = C + I + G + (X − M); taxation influences disposable income and consumption.',[
('1 · Reduction in Private Consumption Expenditure','A lower propensity to consume, or higher propensity to save, reduces C at a given income and shifts AD down. In mature economies, consumption may grow more slowly once many wants are satisfied.'),
('2 · Reduction in Private Investment Expenditure','Poor or bearish business expectations reduce expected returns and investment. Lower I directly reduces planned expenditure, with further effects through the multiplier.'),
('3 · Reduction in Government Expenditure','Budget constraints or spending cuts can reduce government consumption or investment. Both lower AD.'),
('4 · Decline in Exports','Lower foreign purchases mean less expenditure on domestically produced goods and services, reducing AD and domestic income.'),
('5 · Rise in Imports','When buyers switch towards cheaper foreign products, more spending goes to foreign output. Imports enter with a negative sign, reducing demand for domestic output, other things equal.'),
('6 · Increase in Tax Rates','Higher taxes leave households with less disposable income. Consumption can fall even if their propensity to consume is unchanged, pulling AD down.')])
U(9,None,'9.2.4 Consequences of Deficient Demand','Deficient demand: all four consequences','Demand below the full-employment requirement leaves capacity unused. The textbook groups the effects into four situations, with a connected downward spiral.',[
('1 · Underemployment Equilibrium','AD and AS can intersect at output below potential GDP. Firms have no incentive to produce more when planned purchases are insufficient, despite idle resources and involuntary unemployment.'),
('2 · Deflationary Gap','The gap is the shortfall of planned AD from required AD at full-employment output. Weak demand hurts inducement to invest; low investment reduces output and income, which weakens demand again: the low-level equilibrium trap.'),
('3 · Undesired Stocks','Sales fall short of production plans, so unwanted inventories accumulate. Producers may cut prices to clear stocks and reduce future output and employment.'),
('4 · Loss of Profits','Unsold output and price reductions reduce profitability. Bearish expectations can cause another cut in investment, reinforcing weak income and demand.'),
('Overall Effects','Output falls, involuntary unemployment rises and prices face downward pressure. The basic fixed-price income model emphasises falling output; the chapter’s broader discussion also describes deflationary price pressure and contraction in the business cycle.')])
U(9,None,'9.3.3 Causes of Excess Demand','Excess demand: all six causes','Excess demand occurs when planned spending exceeds the AD consistent with full-employment output. The causes reverse the directions of the deficient-demand causes.',[
('1 · Increase in Private Consumption Expenditure','A higher propensity to consume or lower propensity to save raises C at a given income. The demonstration effect—adopting the spending patterns of richer groups—can also increase consumption.'),
('2 · Increase in Private Investment Expenditure','Bullish business expectations and expected high returns raise investment, increasing AD directly and through induced consumption.'),
('3 · Increase in Government Expenditure','Expansion of development and welfare commitments raises government consumption or investment, adding to AD.'),
('4 · Increase in Exports','More foreign demand for domestic output, potentially encouraged by relatively lower domestic prices, raises AD.'),
('5 · Decrease in Imports','Higher foreign prices can shift purchases towards domestic output. A lower M increases net exports and therefore AD, other things equal.'),
('6 · Cut in Tax Rates','Lower taxes leave more disposable income, enabling higher consumption and planned expenditure.')])
U(9,None,'9.3.4 Consequences of Excess Demand','Excess demand: all four consequences','At full employment, with technology and productive capacity given, extra nominal demand cannot create an unlimited increase in real output.',[
('1 · Inflationary Gap','Planned AD exceeds the full-employment requirement. Pressure on fully used resources raises costs and the general price level. Measure the gap vertically at full-employment income.'),
('2 · Static GDP','Real GDP remains at the full-employment level because there is no spare capacity. Nominal GDP can rise as prices rise. Always specify real GDP when saying output remains constant.'),
('3 · Wage–Price Spiral','Higher demand raises pressure on wages and other costs; higher prices raise living costs and wage claims, which can raise costs and prices again. Persistent escalation threatens economic stability.'),
('4 · Loss of Profit from Unfulfilled Demand','The textbook’s point concerns potential profit forgone because producers cannot expand supplies to satisfy additional demand. It is distinct from claiming that every firm’s actual money profit must fall during inflation.'),
('Overall Effects','Real output and employment remain at capacity in this model, while prices rise. Compare this with deficient demand, which can reduce output and employment.')])
U(10,None,'10.4.2 Implications of Budget Deficits','Revenue deficit and fiscal deficit: all implications','Deficit definitions measure different gaps. Their consequences depend on the method of financing, the use of funds and the economy’s available capacity.',[
('Revenue Deficit 1 · Pressure on Welfare Spending','A shortfall of revenue receipts against current expenditure can force cuts to subsidies or welfare programmes, potentially reducing social welfare.'),
('Revenue Deficit 2 · Higher Liabilities','Borrowing from the public, central bank or abroad can finance the shortfall but increases liabilities and future debt-service obligations.'),
('Revenue Deficit 3 · Disinvestment Pressure','Selling public shareholdings can raise funds, but reduces public ownership. The textbook also notes possible increased foreign control when buyers are foreign firms.'),
('Fiscal Deficit 1 · Inflationary Spiral','Central-bank financing can expand money and nominal spending. If output cannot respond because capacity is fully used, prices rise. Inflation is therefore a conditional consequence, not an automatic result of every deficit.'),
('Fiscal Deficit 2 · National Debt','Repeated borrowing increases debt and interest obligations. More resources spent servicing past debt can limit funds for development.'),
('Fiscal Deficit 3 · Vicious Circle of High Deficit and Low Growth','Debt service and fiscal pressures may constrain productive spending; higher taxes can weaken private demand and investment. Weak growth then limits revenue, keeping the deficit high. Productive public investment can instead support growth, so composition matters.'),
('Fiscal Deficit 4 · Crowding-out','Heavy public borrowing can reduce funds available to private investors and put upward pressure on financing costs, discouraging private investment.'),
('Fiscal Deficit 5 · Erosion of Government Credibility','Unsustainable borrowing can weaken confidence and creditworthiness, discourage investors and increase financing difficulty. A deficit used responsibly for productive capacity has different implications from persistent financing of unproductive spending.'),
('Primary Deficit','Primary deficit removes interest on past debt from fiscal deficit. Zero primary deficit means the remaining borrowing requirement equals interest payments; a positive primary deficit indicates an additional gap even before those interest payments.')])
U(10,None,'10.5 Balanced and Unbalanced Budgets','Balanced, surplus and deficit budgets: complete appraisal','A budget’s appropriateness depends on economic conditions. The textbook gives separate merits and demerits for balanced, surplus and deficit budgets.',[
('Balanced Budget · Meaning and Merits','Receipts equal expenditure. Its stated merits are restraint of wasteful expenditure and a signal of financial stability and fiscal discipline.'),
('Balanced Budget · Demerits','It does not necessarily remedy unemployment caused by inadequate AD. In developing economies, insisting on balance can prevent the large initial public-investment push needed for growth.'),
('Surplus Budget · Meaning and Merits','Receipts exceed expenditure. Greater revenue collection and/or lower spending can reduce AD, making a surplus useful against an inflationary gap.'),
('Surplus Budget · Demerits','It can worsen depression by weakening AD further. Persistently suppressing spending can reduce output and employment and contribute to a low-level equilibrium trap.'),
('Deficit Budget · Meaning and Merits','Expenditure exceeds receipts before the financing needed to close the gap. Keynes favoured its use during depression: public spending raises AD directly and can induce further consumption and investment.'),
('Deficit Budget · Demerits','At full employment, additional spending can enlarge excess demand without increasing real output, intensifying inflation and possibly a wage–price spiral. Debt sustainability and the use of borrowed funds also matter.')])
U(10,None,'Ability Zone · Significance of Public Expenditure','Public expenditure: all four importance points','Public expenditure has growth and welfare roles. Explain what the government spends on and the channel through which it affects the economy.',[
('1 · Accelerates GDP Growth','Investment in public enterprises, capital grants for equipment, input subsidies and farm procurement support production and investment. Infrastructure also adds productive capacity.'),
('2 · Promotes Equality','Welfare pensions and access to food, education and healthcare improve the position of poorer households, reducing inequalities in opportunities and living standards.'),
('3 · Restores Economic Stability','During recession, public consumption and investment raise AD. This can interrupt the cycle of weak demand, weak output and weak income.'),
('4 · Creates an Investment-friendly Environment','Roads, dams, bridges and reliable transport reduce private production costs and improve access to markets. This encourages private investment rather than replacing every private activity.')],kind='Ability Zone')
U(11,6,'11.4.1(a) Fixed Exchange Rate System: Merits','Fixed exchange rate: all five merits','A fixed rate is officially set and defended. The chapter’s arguments concern the benefits of greater exchange-rate predictability, subject to successful maintenance of the rate.',[
('1 · Market Stability and Mobility of Capital','Reducing exchange-rate fluctuations lowers one source of uncertainty for international investors and can encourage cross-border capital movement.'),
('2 · Growth of International Trade','Exporters and importers can plan contracts with more predictable domestic-currency returns and costs, supporting international trade.'),
('3 · Stable Macroeconomic Policies','The textbook argues that a stable exchange rate removes frequent exchange-rate changes as a source of policy disturbance. Maintaining the peg still places constraints on policy; it does not give unlimited monetary independence.'),
('4 · Devaluation as a Tool to Expand Foreign Markets','An official downward adjustment in the domestic currency’s value can make exports cheaper to foreigners and improve producers’ international competitiveness, depending on demand responses.'),
('5 · A Check on Inflation','High domestic inflation makes exports less competitive at a fixed rate, weakening receipts and reserves. Pressure to preserve the rate can encourage policies restraining inflation.')])
U(11,None,'11.4.1(b) Fixed Exchange Rate System: Demerits','Fixed exchange rate: all five demerits','The same commitment that provides predictability requires defence and can prevent the official rate from adjusting to market conditions.',[
('1 · Reserves of Forex','The authority needs foreign-exchange reserves to meet excess demand for foreign currency and defend the official rate. Sustained pressure can exhaust reserves.'),
('2 · Inefficient Allocation of Resources','An official rate differing from the market-clearing rate distorts the relative prices guiding production, imports and exports.'),
('3 · Small Size of Forex Market','The chapter argues that a tightly fixed rate limits foreign exchange as an independently traded commodity, restricting the scope of currency-market activity.'),
('4 · Discourages Venture Capital','In the chapter’s usage, this means funds placed in foreign-currency trading to profit from exchange movements. A tightly fixed rate limits these opportunities; this is different from ordinary start-up venture finance.'),
('5 · Divergence from Equilibrium','The official rate can remain above or below the equilibrium rate. Persistent excess demand or supply then requires intervention and can impair efficient production and trade.')])
U(11,None,'11.4.2(a) Flexible Exchange Rate System: Merits','Flexible exchange rate: all five merits','A flexible rate moves with demand and supply. Its advantages arise from allowing prices to adjust rather than defending a prescribed value.',[
('1 · Large Forex Reserves Not Required for Rate Defence','No official peg needs continuous defence. Market adjustment can equilibrate currency demand and supply, although countries may still hold reserves for other reasons.'),
('2 · Efficient Allocation of Resources','Market-clearing exchange rates transmit scarcity and demand signals, helping guide trade, production and investment across countries.'),
('3 · Large Size of Forex Market','Currency itself becomes a traded asset, expanding financial-market activity and related business opportunities.'),
('4 · International Mobility of Liquidity','Less foreign exchange needs to remain committed to defending a fixed rate, potentially freeing funds for international transactions and investment.'),
('5 · Encourages Venture Capital in Currency Trading','Exchange-rate movements create opportunities for investors willing to bear currency risk. This is the chapter’s currency-market meaning of venture capital.')])
U(11,None,'11.4.2(b) Flexible Exchange Rate System: Demerits','Flexible exchange rate: all five demerits','Market adjustment creates uncertainty and can transmit foreign disturbances into the domestic economy.',[
('1 · Marginalisation of Weak Currencies','Low demand for a weak currency can lead to steep depreciation. Imports and foreign-currency obligations become more expensive in domestic money, creating pressure for smaller or vulnerable economies.'),
('2 · Uncertainty of the Market','Frequent exchange-rate changes make future export receipts, import costs and investment returns harder to predict.'),
('3 · Difficulty Maintaining Stable Monetary Policy','Exchange movements affect inflation, capital flows and interest-rate decisions. Responding to them can complicate a stable policy path.'),
('4 · Difficulty with Bilateral Trade Agreements','Changing currency values make it harder to predict the value of payments under long-term trade arrangements. Hedging can reduce, but not eliminate, this problem.'),
('5 · External Shocks','Foreign-currency appreciation can raise the domestic-currency cost of imports even when their foreign price is unchanged. A stronger dollar, for example, increases the rupee bill for a fixed dollar payment.')])
U(11,None,'11.5 Components of Demand for Foreign Exchange','Demand for foreign exchange: all seven components','Foreign exchange is demanded to make payments abroad or acquire foreign-currency assets. Distinguish a change in the exchange rate from other factors shifting demand.',[
('1 · Repayment of International Loans','Foreign-currency loan principal must be repaid in the agreed currency, creating demand for foreign exchange.'),
('2 · Investment in the Rest of the World','Residents buying foreign securities, businesses or other foreign assets need the relevant currency.'),
('3 · Imports','Payments for imported goods and services create demand for foreign exchange.'),
('4 · Direct Purchases Abroad','Foreign travel, study and medical treatment require payments abroad. The chapter includes tourists’ direct purchases here.'),
('5 · Grants and Donations','Unilateral payments sent abroad also require foreign exchange, even though no goods or productive service is received in return.'),
('6 · Payment of Incomes','Factor incomes such as wages, rent, interest and profits paid to non-residents create an outward flow.'),
('7 · Speculative Trading','People may acquire foreign currency expecting its value to rise and hoping to profit from a later sale.'),
('Why Demand Slopes Downward','With ₹ per dollar on the vertical axis, a lower dollar price makes foreign goods and investment cheaper in rupees, increasing demand for dollars, other things equal. A price change causes movement along the curve; other determinants shift it.')])
U(11,None,'11.6 Components of Supply of Foreign Exchange','Supply of foreign exchange: all seven sources','The supply of foreign exchange comes from receipts from abroad and conversion of foreign currency into domestic currency.',[
('1 · Exports','Foreign buyers pay for domestic goods and services, generating foreign-exchange receipts.'),
('2 · Investment from the Rest of the World','Inward FDI and portfolio investment bring foreign funds into the economy.'),
('3 · Direct Purchases by Non-residents','Foreign tourists and other non-residents purchasing domestically contribute foreign-exchange receipts.'),
('4 · Loans from the Rest of the World','Borrowing abroad brings in foreign exchange now, while creating future repayment obligations.'),
('5 · Grants and Donations from Abroad','Foreign assistance, gifts and donations create receipts without a corresponding repayment or current productive service.'),
('6 · Income Receipts','Factor incomes earned from abroad—including wages, interest, rent and profits—bring in foreign exchange.'),
('7 · Remittances by Non-residents','Money sent by non-residents to domestic recipients is a source of foreign exchange. A gift remittance is a transfer, not automatically factor income.'),
('Why Supply Slopes Upward','A higher ₹-per-dollar rate gives more rupees per dollar. It can make domestic goods cheaper for foreign buyers and improve the attractiveness of domestic purchases or investments, increasing foreign-exchange supply, other things equal.')])
U(12,None,'12.3.2 Significance of BoP Accounts / Data','Balance of payments: all five significance points','BoP data reveal the economy’s external position and inform decisions. A single flow should be interpreted with its purpose and the wider account.',[
('1 · Financial Status of the Domestic Economy','The accounts show external receipts, payments and financing needs. Heavy reliance on borrowing can indicate vulnerability or dependence, though borrowing may also finance productive investment.'),
('2 · Net Factor Income from Abroad','Factor-income receipts and payments provide information needed for NFIA, the bridge from domestic income to national income.'),
('3 · Net Exports as a Component of AD','Exports minus imports form part of aggregate demand. A rise in X − M increases demand for domestic output and can raise output and employment where spare capacity exists.'),
('4 · Market Potential','Foreign investment flows can provide evidence about investors’ expectations of market opportunities and returns. Their size is one indicator, not a complete measure, of market potential.'),
('5 · Monetary and Fiscal Policies','External inflows and outflows influence currency demand, reserves and financial conditions, which the RBI considers in monetary policy. Investment flows and the tax environment can also inform fiscal-policy decisions.')])
U(12,None,'12.2–12.3 BoP Balances and Official Reserves','BoP equilibrium, surplus, deficit and reserve movements','The chapter separates ordinary current/capital flows from the official-reserves account. Accounting balance and equilibrium of autonomous transactions are different concepts.',[
('Equilibrium','Ignoring errors and omissions, current-account balance + capital-account balance = zero with no reserve movement. A current-account deficit can be offset by an equal capital-account surplus.'),
('Surplus','Receipts on the relevant non-reserve transactions exceed payments. The authority can acquire foreign assets, increasing official reserves.'),
('Deficit','Payments exceed receipts. A drawdown of reserves or other accommodating finance covers the shortfall.'),
('Reserve Entry versus Reserve Stock','Buying a foreign reserve asset is a use of foreign exchange, while selling a reserve asset provides foreign exchange. An increase in the reserve stock therefore does not mean a credit inflow; follow the sign convention in the question.'),
('Accounting Always Balances','Once counterpart entries and financing are included, total accounts balance. This does not imply the country has no deficit, external debt or financing problem. For example, a current deficit of ₹100 with ordinary capital inflow of ₹60 leaves ₹40 to be financed through reserve use or other accommodation.')])
U(10,None,'10.3.1 Non-tax Receipts','Non-tax revenue: all seven sources','Non-tax receipts arise from sources other than taxes and are part of revenue receipts when they neither create liabilities nor reduce government assets.',[
('1 · Fees','Payments for specified administrative or judicial services, such as passports, registration and court services. The chapter distinguishes these from prices charged for ordinary commercial services.'),
('2 · Fines','Economic penalties for breaking laws. Their primary purpose is enforcement and deterrence rather than raising revenue.'),
('3 · Escheat','Property without a legal heir or valid claimant can pass to the state, generating income for the government under the chapter’s classification.'),
('4 · Special Assessment','Owners may pay when public development raises their property value, helping recover part of the cost of roads, drainage or similar improvements.'),
('5 · Income from Public Enterprises','Profits and dividends from government-owned enterprises provide revenue. Selling government shares is different: it reduces an asset and is a capital receipt.'),
('6 · Spectrum Receipts','The chapter classifies income from allocating telecom spectrum as a non-tax receipt.'),
('7 · Grants and Donations','Assistance and voluntary donations received by government, including during natural calamities, are revenue receipts when they carry no repayment liability.')])
U(10,None,'10.3.2 Plan and Non-plan Expenditure','Plan and non-plan expenditure: the historical distinction','The textbook also explains this older budget classification. It is separate from the revenue/capital classification; learn what each term meant rather than treating them as synonyms.',[
('Plan Expenditure','Expenditure linked to specified development plans and programmes, including central assistance to states. It could include revenue spending, such as assistance, and capital spending, such as roads, bridges and hospitals.'),
('Non-plan Expenditure','Expenditure outside the plan category, including routine government functioning, law and order, defence and subsidies in the chapter’s account.'),
('Two Different Classification Bases','Plan/non-plan asks about a spending programme’s relationship to the planning framework. Revenue/capital asks whether it creates assets or reduces liabilities. Plan expenditure is not automatically capital expenditure.')],kind='Textbook distinction')
U(12,6,'Ability Zone · Causes of Disequilibrium in BoP','BoP disequilibrium: all economic, political and social causes','Disequilibrium can result from changes in trade or capital flows. A factor can improve or worsen the position depending on the direction of the change.',[
('Economic 1 · Development Expenditure','Large development programmes can require substantial imports of equipment and inputs, increasing foreign payments and potentially creating a deficit.'),
('Economic 2 · Business Cycles','Depression abroad may reduce demand for exports; expansion abroad can raise it. The effect depends on the countries affected and the response of imports and other flows.'),
('Economic 3 · Domestic Inflation','Higher domestic prices can make imports relatively attractive and exports less competitive, worsening the external balance.'),
('Economic 4 · Import Substitutes','Domestic alternatives reduce import requirements and can improve the balance, provided their production is viable.'),
('Economic 5 · Changing Cost Structure','Technological or managerial improvements alter relative competitiveness. Favourable domestic cost changes can increase exports; improvements by trading partners can have the opposite effect.'),
('Political 1 · Instability','Uncertainty can discourage direct and portfolio investment, reducing capital inflows or causing withdrawals.'),
('Political 2 · Government Policy','Large cuts in import duties can encourage imports and widen a current-account deficit, other things equal. Other policy changes can alter trade and investment incentives.'),
('Social 1 · Tastes and Preferences','Changing consumer preferences can raise exports when foreign demand favours domestic products, or raise imports when residents prefer foreign goods.'),
('Social 2 · Cross-border Prejudices','Political or social hostility can divert trade towards costlier import sources or less profitable export markets, weakening the external position.')],kind='Ability Zone')
U(2,None,'2.5–2.6 Four Sectors and Intersectoral Interdependence','Four sectors and the flows connecting them','Each sector depends on other sectors. Real flows move goods and services; money flows record the corresponding payments and receipts.',[
('Household Sector','Households consume goods and services and own factors of production. They supply land, labour, capital and entrepreneurial services to producers and receive factor incomes.'),
('Producer Sector','Firms hire or purchase factor services and combine them with intermediate inputs to produce goods and services. They depend on households for inputs and demand.'),
('Government Sector','Government provides welfare, administration, law and order and defence, and also acts as a producer. It depends on households and firms for tax and non-tax revenue; they depend on it for public services.'),
('External Sector','The rest of the world connects through exports, imports and cross-border capital flows. A closed economy excludes this sector; an open economy includes it.'),
('Real Flows','Factor services move from households to firms; goods and services move from firms to households. These are actual resource and output flows.'),
('Money Flows','Factor payments move from firms to households; consumption expenditure moves from households to firms. They travel opposite to the corresponding real flows and keep income circulating.')])

# Expand remaining material that points at removed scans, and preserve all existing diagrams.
for c in d['chapters'][:12]:
 for l in c['lessons']:
  l['body']=l['body'].replace('Check the Ability Zone for ships, aircraft, fishing vessels and other special cases.','Ships, aircraft, fishing vessels and floating platforms require the domestic-territory tests explained in the special-cases section.').replace('The original comparison covers the full list of merits and demerits.','The four appraisal sections below explain all five merits and five demerits of each system.').replace('Read the Ability Zone worked table to see a current-account deficit offset by capital inflows.','For example, a current-account deficit of 100 can be financed by capital inflows of 100; accounting balance coexists with the current-account shortfall.')
# Full written practice for every restored section; old checked MCQ progress is retained.
for ch,l in changed:
 qid='macro-review-'+ch+'-'+l['key']
 d['questions']=[q for q in d['questions'] if q['id']!=qid]
 d['questions'].append(dict(id=qid,chapter=ch,type='theory',marks=6,tag='Full-topic review',q='Explain: '+l['title']+'. Use the relevant headings and reasons.',solution=l['title']+'\n'+l['body'].replace('\n\n','\n')))
p.write_text('window.ECON='+json.dumps(d,ensure_ascii=False,separators=(',',':'))+';\n')
print('Restored sections:',len(changed),'Total lessons:',sum(len(c['lessons']) for c in d['chapters']),'Questions:',len(d['questions']))
