from pathlib import Path
import json
p=Path(__file__).resolve().parents[1]/'dist/content.js';d=json.loads(p.read_text()[12:].rstrip(';\n'))
# Each line becomes a distinct explained point; the final sentence connects the concept.
lessons={
'i1':[
('Before British rule: strong handicrafts, especially textiles, alongside a mainly agricultural economy.|Colonial policy: turn India into a raw-material supplier and a market for British manufactured goods.|Result: slow growth, low productivity, weak industry and widespread poverty.','The economy was organised around British needs, which explains the weaknesses in every sector.'),
('Exploitative land settlement: high rent and insecure tenure left cultivators with little money or reason to improve land.|Low investment: poor irrigation, old techniques and limited inputs kept yields low.|Small, fragmented holdings: scattered plots made efficient cultivation difficult.','Most people depended on farming, but dependence is not the same as productivity.'),
('Subsistence farming: grow mainly for the family’s own use.|Commercial farming: grow mainly for sale, including colonial cash crops such as cotton and jute.|The problem: pressure to grow cash crops could reduce food cultivation without improving farmers’ incomes.','Commercialisation describes where the crop goes; it does not guarantee that the farmer benefits.'),
('British machine-made imports competed with Indian handmade goods.|Discriminatory duties weakened Indian goods in foreign markets while favouring British goods in India.|Loss of royal patronage reduced demand for specialised crafts.|Displaced artisans moved towards agriculture because modern industry could not absorb them.','De-industrialisation = handicrafts decline without enough modern industry to replace them.'),
('Cotton mills developed mainly in western India; jute mills were concentrated in Bengal.|Iron and steel emerged later, including TISCO in 1907.|Capital-goods industries remained weak, limiting the ability to make machinery.|Modern industry grew too slowly to employ displaced artisans.','A few successful industries existed, but the overall industrial base remained narrow.'),
('Trade pattern: export raw materials; import manufactured goods.|British control: trade served Britain’s factories and markets; the Suez Canal strengthened these links.|Drain of wealth: export earnings financed British administration, wars and payments abroad.','Export surplus means exports exceed imports. It helped India only if the resulting resources stayed and supported development.'),
('Poor health: high death and infant-mortality rates, low life expectancy, disease and inadequate sanitation.|Low literacy: education reached few people, especially women.|1921: the Year of the Great Divide—population growth became more consistently positive afterwards.','High birth and death rates initially kept population growth modest; falling death rates later widened the gap.'),
('Occupational structure = how workers are distributed across sectors.|About 70–75% worked in the primary sector; industry employed only about 10% in the textbook’s colonial summary.|Weak non-farm opportunities pushed extra workers onto land, lowering average output per worker.','Employment share tells you where people work; GDP share tells you where output is produced.'),
('Colonial purpose: move raw materials, sell British goods, transport troops and administer India.|Infrastructure built: railways, ports, post and telegraph; rural roads and social facilities remained inadequate.|Side effects: better transport, communication and links between regions.','A balanced answer recognises the benefits while explaining that colonial interests determined the priorities.')],
'i2':[
('Capitalist economy: private ownership; markets and profit guide production.|Socialist economy: government ownership and planning guide resource use.|Mixed economy: public and private sectors coexist; India used public leadership with regulated private enterprise.','India wanted industrial growth while also pursuing social welfare and equity.'),
('Planning = deliberately allocating resources towards stated goals over a fixed period.|India’s First Five Year Plan began in 1951.|Plans coordinated investment in agriculture, industry and infrastructure when resources were scarce.','Common goals stayed broadly similar, but the priority given to each sector could change between plans.'),
('Growth: increase productive capacity and output.|Modernisation: adopt better technology and a progressive social outlook, including women’s participation.|Self-reliance: reduce dependence on foreign resources for essential needs.|Equity: ensure benefits reach all sections and basic needs are met.','More GDP does not automatically mean fairer distribution; growth and equity are separate goals.'),
('Abolition of intermediaries: remove rent-collecting middlemen and connect cultivators directly with the state.|Land ceiling: limit holdings and redistribute surplus land.|Consolidation: combine scattered plots; cooperative farming: pool resources.|Limitation: loopholes, litigation and weak implementation reduced the gains.','Institutional reforms change ownership and tenure; technical reforms change production methods.'),
('Green Revolution = a sharp rise in agricultural output through HYV technology.|The package: HYV seeds + irrigation + fertilisers + pesticides + credit.|Early gains concentrated in wheat and well-irrigated regions; later gains spread to more crops and areas.','Seeds alone cannot deliver the promised yield when irrigation and supporting inputs are missing.'),
('Higher yields raised foodgrain production and reduced dependence on imports.|More marketable surplus supplied people outside agriculture.|Better food supplies supported buffer stocks and price stability.|Higher farm incomes increased demand for industrial goods.','Marketable surplus = production left for sale after the farmer’s own requirements.'),
('Crop imbalance: early gains mainly benefited wheat and rice.|Regional imbalance: well-irrigated regions advanced faster.|Income inequality: larger farmers could afford the input package more easily.|Environmental damage: excessive chemicals and groundwater use harmed soil and water.','Evaluate both the increase in food output and how its gains and costs were distributed.'),
('In favour: subsidies make inputs affordable, encourage new technology and support small farmers.|Against: benefits may favour large farmers; government spending rises; cheap inputs can encourage waste.|Better design: target farmers who need support and discourage excessive input use.','The issue is who receives the subsidy and what behaviour it encourages.'),
('Basic and heavy industries needed large investments and long waiting periods before returns.|Private firms often lacked the capital or incentive to undertake them.|The public sector supplied infrastructure, strategic industries and investment in backward regions.','Public-sector leadership supported a mixed economy; it did not mean private firms disappeared.'),
('IPR 1956: one group reserved for the state; a second with state leadership and private participation; the remainder open to regulated private enterprise.|Industrial licensing controlled new factories and expansion.|Purpose: direct scarce resources and promote regional balance; drawback: too many controls weakened competition.','Remember the three groups by the degree of state involvement, rather than as an unexplained list.'),
('Karve Committee, 1955: emphasised small industries’ role in rural development.|Why protect them? They create jobs with relatively little capital and spread production across regions.|Support: reserved products, concessions and credit.|Weaknesses: limited finance, outdated technology and marketing difficulties.','Their main advantage was labour-intensive, decentralised growth.'),
('Import substitution = make domestically what was previously imported.|Tariff: tax imports, making them costlier. Quota: limit their quantity.|Benefit: protect young domestic industries and conserve foreign exchange.|Cost: prolonged protection weakens pressure to improve quality and efficiency.','Protection can help an industry get started; permanent shelter can make it complacent.'),
('Strategy: public-sector leadership, licensing, small-industry protection and import substitution.|Achievements: a wider industrial base, infrastructure and greater food security.|Limitations: inefficient enterprises, restrictive controls, weak job creation and persistent poverty.','The pre-reform strategy built capacity, but its limitations created pressure for change.')],
'i3':[
('Fiscal pressure: spending exceeded revenue, increasing borrowing and debt.|External crisis: foreign-exchange reserves fell to roughly two weeks of imports.|Other problems: inflation and weak public-enterprise returns.|Response: assistance from IMF/World Bank and a shift towards a more competitive economy.','1991 combined an immediate payments crisis with deeper weaknesses in the old growth strategy.'),
('Liberalisation = reduce direct government controls over producing units.|Industrial changes: reduce licensing, open more activities to private firms, ease expansion and imports of capital goods.|Mechanism: easier entry → more competition → pressure to improve efficiency.','Fewer controls does not mean no regulation; safety, competition and other safeguards still matter.'),
('Increase competition by allowing more private and foreign participation in finance.|Give banks more operational freedom within safeguards.|Shift RBI’s emphasis from detailed control towards facilitation and regulation.','RBI becoming a facilitator does not mean it stopped supervising banks.'),
('Tax reforms: simplify taxes, rationalise rates, widen the tax base and improve compliance.|GST, 1 July 2017: brought many indirect taxes into a common framework.|Demonetisation, November 2016: withdrew legal-tender status of the then ₹500/₹1,000 notes, aiming to address unaccounted money and encourage formal/digital activity.','Keep a policy’s objective separate from whether it fully achieved that objective.'),
('1991 devaluation: officially lower the rupee’s value to improve export competitiveness and tackle the external crisis.|Trade reforms: reduce tariffs, quantitative restrictions and licensing barriers.|Effect: cheaper exports in foreign-currency terms, costlier imports in rupees and greater competition for domestic firms.','Devaluation is an official change; depreciation is a market-driven fall in currency value.'),
('Privatisation: greater private ownership or management of public enterprises.|Disinvestment: sale of government equity; a minority sale need not transfer control.|Possible gains: efficiency, commercial discipline and revenue.|Concerns: undervaluation, job losses and loss of future public income.','Ask whether ownership or control actually changed before calling a sale full privatisation.'),
('Selected public enterprises received greater financial and managerial freedom.|Navratna/Maharatna arrangements aim to support quicker commercial decisions.|The enterprise can remain government-owned while gaining autonomy.','Autonomy changes decision-making freedom; privatisation changes the private sector’s role in ownership or management.'),
('Globalisation = deeper integration through trade, investment, technology and services.|Outsourcing = hiring an external provider for particular work.|India’s advantages: skilled English-speaking workers, relatively low costs, IT links and time-zone differences.','An overseas company using an Indian accounting service is outsourcing; the wider cross-border integration is globalisation.'),
('WTO began in 1995, succeeding GATT.|Role: multilateral trade rules, negotiations and dispute settlement.|Debate: developing countries face unequal bargaining power and competition from subsidised producers in richer countries.','Explain its intended rules-based role, then assess whether the gains are distributed fairly.'),
('Competition and choice: firms face pressure to improve quality; consumers get more options.|Investment and technology: foreign links can bring finance, knowledge and market access.|Growth and external strength: the textbook highlights faster growth and stronger forex reserves over particular periods.','Use a cause-and-effect chain, not just “reforms were good”: competition → efficiency → better products.'),
('Agriculture: reduced support and foreign competition hurt some producers.|Industry and jobs: import competition and capital-intensive growth limited gains for some firms/workers.|Unequal development: benefits concentrated in certain sectors, cities and income groups.|Other concerns: disinvestment, fiscal priorities, economic dependence and consumerism.','Reforms can raise total output while leaving particular people or sectors behind.')],
'i4':[
('Human resource: people’s abilities to contribute to production.|Human capital: the stock of their skills, knowledge and health.|Human capital formation: adding to that stock through education, training and health investment.','Population counts people; human capital asks what they are able to do.'),
('Human capital view: education and health are means to higher productivity and income.|Human development view: education, health, freedom and well-being are valuable ends in themselves.|Implication: people deserve health and education even without an immediate measured productivity gain.','Same services, different ultimate purpose: productive returns versus a better human life.'),
('Physical capital: tangible, separable from its owner and saleable as an asset.|Human capital: embodied in a person; only its services can be sold.|Both depreciate, but learning and health investment can counter the loss of human capability.|Human capital also creates social benefits, such as informed citizenship.','A machine can be sold separately; a driver’s skill cannot be separated from the driver.'),
('Education builds knowledge, skills and earning capacity.|Health increases efficiency and reduces working time lost to illness.|Health spending includes preventive care, treatment, awareness, hygiene and sanitation.','They complement each other: a sick worker cannot fully use even excellent skills.'),
('On-the-job training: learn skills needed in actual work.|Adult study: update knowledge and capabilities after initial schooling.|Migration: bear travel/settlement costs to reach better opportunities.|Information: spend to find suitable education and jobs.','Each is an investment when its cost is expected to produce future benefits.'),
('Change in emotional/material environment: education encourages new ideas and techniques.|Higher productivity of physical capital: skilled workers use machines better.|Higher participation and equality: more people can join and benefit from growth.','The relationship runs both ways: capabilities support growth, and growth finances better education and health.'),
('Rising population stretches education and health resources.|Brain drain reduces domestic access to skilled people.|Deficient manpower planning creates a skills–jobs mismatch.|Insufficient primary-sector training and low academic standards weaken practical capability.','Qualifications improve human capital only when they bring usable knowledge and skills.'),
('Good citizenship and broader horizons: people make more informed choices.|Science, technology and resource use: better knowledge improves production.|Culture and personality: education develops people beyond their jobs.|Participation: more people can contribute to development.','Education generates both private returns and benefits for society.'),
('Public intervention widens access when private prices exclude poorer households.|Government also finances costly facilities and sets quality standards.|Kothari Commission: education spending of 6% of GDP.|RTE Act, 2009: free and compulsory education for ages 6–14.','Spending as a share of GDP and as a share of the government budget have different denominators.'),
('Achievements: more schools, higher education, literacy and technical skills support a knowledge economy.|Access gaps: illiteracy, gender bias, low rural access and expensive private provision.|Quality gap: weak vocationalisation and insufficient public spending.|Steep education pyramid: fewer people reach each higher level.','Access gets people into education; quality and relevant skills determine what they gain.')],
'i5':[
('Rural development addresses economic, social and environmental problems together.|Priorities: education/health, land and productive resources, infrastructure, credit and marketing.|Diversification and poverty reduction create livelihoods beyond seasonal crop work.','Improving rural life is broader than simply increasing farm output.'),
('Short-term credit pays for seeds, fertilisers, wages and needs before harvest income arrives.|Long-term credit pays for machinery, irrigation and land improvement.|Institutional sources: cooperatives, banks, RRBs and land-development banks.|Non-institutional sources: moneylenders, landlords and traders.','The timing gap between spending on a crop and earning from it explains the need for credit.'),
('NABARD, 1982: apex institution supporting and coordinating rural credit/development.|SHGs pool members’ small savings and lend within the group, often linking to banks.|Micro-credit can reach borrowers without conventional collateral and support women’s participation.','Small loans help inclusion; viable work, skills and market access determine whether incomes improve.'),
('Unequal access: small farmers may still depend on informal lenders.|Delays, paperwork and collateral make institutional credit hard to obtain.|Crop failure and unproductive borrowing make repayment difficult.|Overdues weaken lenders and restrict future credit.','Good credit needs the right timing, terms and productive use—not just a larger loan.'),
('Marketing includes gathering, processing, grading, packing, storage, transport and sale.|Defects: faulty weights, poor information, weak transport/storage and large intermediary margins.|Distress sale: urgent cash needs force farmers to sell cheaply after harvest.','Credit and marketing are linked: debt pressure plus no storage weakens the farmer’s bargaining power.'),
('Regulated markets improve fairness; roads, storage and information reduce losses.|Cooperatives pool produce and strengthen bargaining.|MSP, procurement, buffer stocks and PDS support the food-marketing system.|Direct markets reduce intermediaries; contracts offer markets but can create bargaining risks.','Different measures fix different problems: storage addresses timing; market information addresses bargaining.'),
('Crop diversification changes the mix of crops; broader diversification adds allied/non-farm work.|Why? Spread risk, earn outside the crop season and absorb surplus farm labour.|Options: animal husbandry, fisheries, horticulture, processing and rural services.','Diversification turns a single seasonal income source into several livelihood opportunities.'),
('Animal husbandry supplies milk, eggs and meat, adding income alongside crops.|Operation Flood: milk cooperatives linked producers and consumers, supporting the White Revolution.|Fisheries create jobs but need finance, equipment, storage and protection from pollution.|Veterinary care, feed and better breeds raise livestock productivity.','Allied activities reduce dependence on crops, but still require reliable support services and markets.'),
('Horticulture: fruits, vegetables, flowers and plantation crops can raise incomes and improve nutrition.|Perishability makes cold chains, transport and processing important.|IT provides weather, prices, advice and links to work/markets.|Electricity, connectivity and skills determine who benefits from IT.','Producing a valuable crop is only half the task; getting it to buyers without spoilage is the other half.'),
('Organic farming uses organic inputs and ecological methods rather than synthetic chemicals.|Benefits: healthier soil, less pollution and lower dependence on non-renewable chemical inputs.|Textbook headings also emphasise healthier food, inexpensive technology and potential export premiums.|India’s abundant labour can support labour-intensive organic methods.','Keep the environmental benefits clear; premium prices and lower costs are possibilities, not guarantees.'),
('Constraints: lower transition yields, high cost per unit and shorter shelf life.|Farmers need training, suitable inputs, certification and marketing.|PRANAM box: encourage alternative nutrients and balanced fertiliser use to protect soil health.','Organic farming becomes viable when production support is matched by a reliable market.')],
'i6':[
('A worker participates in an economic activity producing goods or services.|Self-employed and hired workers both count.|Unpaid family helpers in a farm/business can count even without a separate wage.|Own-family domestic services are generally outside measured employment.','Do not confuse “no wage” with “no economic production”.'),
('Self-employed: operate their own enterprise, such as a shop owner.|Regular salaried: continuing employment with regular pay.|Casual wage labourer: hired for short periods/tasks, such as a daily-wage construction worker.','Employment status tells you the work relationship; construction or agriculture tells you the sector.'),
('Workforce: people actually employed.|Labour force: employed people plus unemployed people willing and available for work.|Labour supply: the hours/services people offer at a wage.|Someone not seeking or available for work is outside the labour force, rather than automatically unemployed.','Worker-population ratio uses population; unemployment rate uses labour force. Always check the denominator.'),
('Rural work participation reflects farming, family labour and the need to earn even in low-productivity work.|Urban patterns differ because of education and the available jobs.|Women face care responsibilities, social barriers and under-recording of economic activity.','A lower measured participation rate does not mean women make no productive contribution.'),
('Primary: agriculture and allied activities.|Secondary: manufacturing and construction. Tertiary: services.|Rural workers are more concentrated in farming; urban work is more concentrated outside it.|A high farm employment share with a low farm GDP share signals low average output per worker.','Development needs productive non-farm jobs, not just movement out of agriculture.'),
('Jobless growth: GDP rises faster than employment opportunities.|Capital-intensive technology and productivity gains can raise output without many new jobs.|Responses: labour-intensive activities, small enterprises, relevant skills and rural diversification.','It means inadequate job creation relative to growth—not necessarily zero new jobs in every year.'),
('Casualisation: a rising share of casual wage work rather than secure regular jobs/self-employment.|Surplus rural labour migrates; limited jobs and weak bargaining power encourage daily-wage hiring.|Consequences: insecurity and fewer benefits.','The concept describes a process; check actual table years before claiming the casual share always rose.'),
('Formal sector: government/public enterprises and private establishments with ten or more workers in the textbook definition.|Informal sector: smaller private enterprises, farming and self-employment.|Informalisation: more employment without formal protection and social-security benefits.','Casualisation concerns job status; informalisation concerns organisation and protection. They can overlap.'),
('Open: willing and able to work, but unable to get a job.|Disguised: extra workers can leave without reducing output; their marginal productivity is zero.|Seasonal: work disappears outside the working season.|Educated/structural: qualifications or skills do not match available opportunities.','If two people leave a family farm and output stays the same, those two were disguisedly unemployed.'),
('Slow job growth and rapid population growth widen the employment gap.|Seasonal farming and inadequate irrigation leave people without year-round work.|Joint-family farming can conceal surplus labour; declining cottage industries reduce alternatives.|Low investment, skills mismatch and limited mobility restrict opportunities.','Explain the mechanism after the heading: inadequate irrigation → fewer crop seasons → seasonal unemployment.'),
('Direct employment: government hires workers itself. Indirect: public activity raises demand and jobs in other firms.|MGNREGA: at least 100 days of unskilled manual wage work per financial year for a rural household whose adults volunteer.|Work is to be provided within 15 days of demand; eligible failure attracts unemployment allowance.|Skills, rural livelihoods, roads and small-business support create other opportunities.','The MGNREGA entitlement is per household, not 100 days separately for every adult.')]
}
for c in d['chapters']:
 if c['id'] not in lessons:continue
 assert len(c['lessons'])==len(lessons[c['id']])
 for j,(l,(pts,take)) in enumerate(zip(c['lessons'],lessons[c['id']])):
  l['points']=pts.split('|');l['takeaway']=take;l['body']='\n\n'.join(l['points'])+'\n\n'+take;l['kind']='Understand & remember'
  q=next(q for q in d['questions'] if q['id']==f"ied-theory-{c['number']}-{j}")
  q['solution']=l['title']+'\n'+'\n'.join(f'{i+1}. {point}' for i,point in enumerate(l['points']))+'\n'+take+ ('\n'+l['formula'] if l['formula'] else '')
p.write_text('window.ECON='+json.dumps(d,ensure_ascii=False,separators=(',',':'))+';\n')
